name: Build Web

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - run: flutter pub get

      - name: Build Web avec Version Dynamique
        shell: bash
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //g' | cut -d'+' -f1)
          flutter build web --release --dart-define=APP_VERSION="$VERSION+${{ github.run_number }}"

      - name: Upload Web App
        uses: actions/upload-artifact@v4
        with:
          name: laststats-web-app
          path: build/web/